version: '3.9'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tms_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app:ro
      - ./app/requirements.txt:/app/requirements.txt:ro
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/tmsdb
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: tms_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tms_redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tms_celery_worker
    command: celery -A celery_app.tasks worker --loglevel=info
    volumes:
      - ./app:/app:ro
      - ./app/requirements.txt:/app/requirements.txt:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/tmsdb
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
      - redis
      - web

volumes:
  pgdata:
